// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kaushal02/terraform-provider-awsapigateway/provider (interfaces: AwsApiGatewayProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	provider "github.com/kaushal02/terraform-provider-awsapigateway/provider"
)

// MockAwsApiGatewayProvider is a mock of AwsApiGatewayProvider interface.
type MockAwsApiGatewayProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAwsApiGatewayProviderMockRecorder
}

// MockAwsApiGatewayProviderMockRecorder is the mock recorder for MockAwsApiGatewayProvider.
type MockAwsApiGatewayProviderMockRecorder struct {
	mock *MockAwsApiGatewayProvider
}

// NewMockAwsApiGatewayProvider creates a new mock instance.
func NewMockAwsApiGatewayProvider(ctrl *gomock.Controller) *MockAwsApiGatewayProvider {
	mock := &MockAwsApiGatewayProvider{ctrl: ctrl}
	mock.recorder = &MockAwsApiGatewayProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAwsApiGatewayProvider) EXPECT() *MockAwsApiGatewayProviderMockRecorder {
	return m.recorder
}

// getApiGatewayClient mocks base method.
func (m *MockAwsApiGatewayProvider) getApiGatewayClient() provider.AwsApiGatewayClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getApiGatewayClient")
	ret0, _ := ret[0].(provider.AwsApiGatewayClient)
	return ret0
}

// getApiGatewayClient indicates an expected call of getApiGatewayClient.
func (mr *MockAwsApiGatewayProviderMockRecorder) getApiGatewayClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getApiGatewayClient", reflect.TypeOf((*MockAwsApiGatewayProvider)(nil).getApiGatewayClient))
}

// getApiGatewayV2Client mocks base method.
func (m *MockAwsApiGatewayProvider) getApiGatewayV2Client() provider.AwsApiGatewayV2Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getApiGatewayV2Client")
	ret0, _ := ret[0].(provider.AwsApiGatewayV2Client)
	return ret0
}

// getApiGatewayV2Client indicates an expected call of getApiGatewayV2Client.
func (mr *MockAwsApiGatewayProviderMockRecorder) getApiGatewayV2Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getApiGatewayV2Client", reflect.TypeOf((*MockAwsApiGatewayProvider)(nil).getApiGatewayV2Client))
}

// getAwsGetRestApisPaginator mocks base method.
func (m *MockAwsApiGatewayProvider) getAwsGetRestApisPaginator() provider.AwsGetRestApisPaginator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getAwsGetRestApisPaginator")
	ret0, _ := ret[0].(provider.AwsGetRestApisPaginator)
	return ret0
}

// getAwsGetRestApisPaginator indicates an expected call of getAwsGetRestApisPaginator.
func (mr *MockAwsApiGatewayProviderMockRecorder) getAwsGetRestApisPaginator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getAwsGetRestApisPaginator", reflect.TypeOf((*MockAwsApiGatewayProvider)(nil).getAwsGetRestApisPaginator))
}
